---

- name: Edit /etc/default/grub
  hosts: all
  vars:
    grub_conf: /etc/default/grub
  tasks:

  - name: Check if file contain GRUB_CMDLINE_LINUX
    lineinfile:
      path: "{{ grub_conf }}"
      regex: '^GRUB_CMDLINE_LINUX'
      state: absent
    check_mode: on
    register: result
    changed_when: false

  - name: Add GRUB_CMDLINE_LINUX and our parameters
    lineinfile:
      path: "{{ grub_conf }}"
      line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
    when: not result.found
    notify: Run grub2-mkconfig

  - name: Check if file is already ok
    lineinfile:
      path: "{{ grub_conf }}"
      regex: '^GRUB_CMDLINE_LINUX=.*net.ifnames=0 biosdevname=0.*'
      state: absent
    check_mode: on
    register: result
    changed_when: false

  - name: Set net.ifnames and biosdevname
    lineinfile:
      path: "{{ grub_conf }}"
      regexp: '^(GRUB_CMDLINE_LINUX=.*)"$'
      line: '\1 net.ifnames=0 biosdevname=0"'
      backrefs: yes
    when: not result.found
    notify: Run grub2-mkconfig

  handlers:
  - name: Run grub2-mkconfig
    command: grub2-mkconfig
