---
- name: Install and configure httpd
  hosts: nodes
  tasks:

  - name: Install httpd package
    yum:
      name: httpd
      state: latest

  - name: Enable and start httpd service
    service:
      name: httpd
      enabled: yes
      state: started

  - name: Copy index.html file
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: Enable and start firewalld
    service:
      name: firewalld
      enabled: yes
      state: started

  - name: Open firewall port
    firewalld:
      service: http
      permanent: yes
      state: enabled
    notify: Reload firewalld rules

  handlers:
    - name: Reload firewalld rules
      command:
        cmd: firewall-cmd --reload


