- name: Uninstall httpd
  hosts: nodes
  tasks:

#  - name: Stop and disable httpd service
#    service:
#      name: httpd
#      enabled: no
#      state: stopped

  - name: Remove httpd package
    yum:
      name: httpd
      state: absent

  - name: Delete index.html file
    file:
      path: /var/www/html/index.html
      state: absent

  - name: Enable and start firewalld
    service:
      name: firewalld
      enabled: yes
      state: started

  - name: Close firewall port
    firewalld:
      service: http
      permanent: yes
      state: disabled
    notify: Reload firewalld rules

  handlers:
    - name: Reload firewalld rules
      command:
        cmd: firewall-cmd --reload


